version: '3'

# dev environment on our server
services:
  solr:
    image: 'solr:6-alpine'
    container_name: 'solr'
    restart: always
    volumes:
      - './solr:/opt/solr/server/solr/tester'
    ports:
      - '8983:8983'
  app:
    build: .
    image: 'laurielias/ajapaik-web:latest'
    container_name: 'ajapaik'
    entrypoint: '/usr/local/bin/docker-entrypoint-dev.sh'
    ports:
      - '8000:8000'
    links:
      - solr
    volumes:
      - './:/home/docker/ajapaik'
      - './media:/home/docker/ajapaik/media'