# Generated by Django 2.2.17 on 2020-12-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ajapaik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionRectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectPhoto', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads',
                                                   verbose_name='SubjectPhoto')),
                ('origin',
                 models.PositiveSmallIntegerField(choices=[(0, 'User'), (1, 'Algorithm'), (2, 'Picasa')], default=1)),
                ('gender', models.PositiveSmallIntegerField(blank=True,
                                                            choices=[(0, 'Female'), (1, 'Male'), (2, 'Unknown'),
                                                                     (3, 'Not Applicable')], null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True,
                                                         choices=[(0, 'Child'), (1, 'Adult'), (2, 'Elderly'),
                                                                  (3, 'Unknown'), (4, 'Not Applicable')], null=True)),
                ('coordinates', models.TextField()),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='face_recognition_rectangles', to='ajapaik.Photo')),
                ('subject_ai_suggestion',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='face_recognition_ai_detected_rectangles', to='ajapaik.Album')),
                ('subject_consensus',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='face_recognition_crowdsourced_rectangles', to='ajapaik.Album')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='face_recognition_rectangles', to='ajapaik.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecognitionUserSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin',
                 models.PositiveSmallIntegerField(choices=[(0, 'User'), (1, 'Algorithm'), (2, 'Picasa')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rectangle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='face_recognition_suggestions',
                                                to='ajapaik_face_recognition.FaceRecognitionRectangle')),
                ('subject_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='face_recognition_suggestions', to='ajapaik.Album')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='face_recognition_suggestions', to='ajapaik.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecognitionRectangleSubjectDataSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(
                    choices=[(0, 'Female'), (1, 'Male'), (2, 'Unknown'), (3, 'Not Applicable')], null=True)),
                ('age', models.PositiveSmallIntegerField(
                    choices=[(0, 'Child'), (1, 'Adult'), (2, 'Elderly'), (3, 'Unknown'), (4, 'Not Applicable')],
                    null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('face_recognition_rectangle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                                 related_name='face_recognition_rectangle',
                                                                 to='ajapaik_face_recognition.FaceRecognitionRectangle')),
                ('proposer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_data_proposer',
                                   to='ajapaik.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecognitionRectangleFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('is_correct_person', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('alternative_subject',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Album')),
                ('rectangle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback',
                                                to='ajapaik_face_recognition.FaceRecognitionRectangle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='face_recognition_rectangle_feedback', to='ajapaik.Profile')),
            ],
        ),
    ]
