# Generated by Django 3.2.16 on 2022-11-06 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik_face_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognitionrectanglesubjectdatasuggestion',
            name='face_recognition_rectangle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='face_recognition_suggestion_subject_datas',
                                    to='ajapaik_face_recognition.facerecognitionrectangle'),
        ),
    ]
