# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik_face_recognition', '0091_auto_20190306_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognitionrectangle',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kasutaja'), (1, 'Algoritm'), (2, 'Picasa')], default=1),
        ),
        migrations.AlterField(
            model_name='facerecognitionuserguess',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kasutaja'), (1, 'Algoritm'), (2, 'Picasa')], default=1),
        ),
    ]
