# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0105_auto_20190801_2122'),
        ('ajapaik_face_recognition', '0093_auto_20190801_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionrectanglefeedback',
            name='alternative_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_rectangle_feedback', to='ajapaik.Album'),
        ),
    ]
