# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0105_auto_20190812_1906'),
        ('ajapaik_face_recognition', '0095_auto_20190809_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionrectanglefeedback',
            name='alternative_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Album'),
        ),
        migrations.AddField(
            model_name='facerecognitionrectanglefeedback',
            name='is_correct_person',
            field=models.NullBooleanField(),
        ),
    ]
