# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik_face_recognition', '0095_auto_20190809_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionrectangle',
            name='age',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Young'), (1, 'Middleage'), (2, 'Old')], null=True),
        ),
        migrations.AddField(
            model_name='facerecognitionrectangle',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Mees'), (1, 'Naine')], null=True),
        ),
    ]
