# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0106_auto_20190924_0044'),
        ('ajapaik_face_recognition', '0096_auto_20190908_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionRectangleSubjectDataGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Mees'), (1, 'Naine')], null=True)),
                ('age', models.PositiveSmallIntegerField(choices=[(0, 'Young'), (1, 'Middleage'), (2, 'Old')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('face_recognition_rectangle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_rectangle', to='ajapaik_face_recognition.FaceRecognitionRectangle')),
                ('guesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_data_guesser', to='ajapaik.Profile')),
            ],
        ),
    ]
