# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0116_transcription_modified'),
        ('ajapaik_face_recognition', '0103_auto_20191001_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionrectanglefeedback',
            name='alternative_subject',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, to='ajapaik.Album'),
        ),
        migrations.AddField(
            model_name='facerecognitionrectanglefeedback',
            name='is_correct_person',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectangle',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Laps'), (1, 'Täiskasvanu'), (2, 'Eakas'), (3, 'Tundmatu'), (4, 'Ei kehti')], null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectangle',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Naine'), (1, 'Mees'), (2, 'Tundmatu'), (3, 'Ei kehti')], null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectanglesubjectdataguess',
            name='age',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Laps'), (1, 'Täiskasvanu'), (2, 'Eakas'), (3, 'Tundmatu'), (4, 'Ei kehti')], null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectanglesubjectdataguess',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Naine'), (1, 'Mees'), (2, 'Tundmatu'), (3, 'Ei kehti')], null=True),
        ),
    ]
