# Generated by Django 2.2.16 on 2020-10-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik_face_recognition', '0104_auto_20200112_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaceRecognitionUserGuess',
            new_name='FaceRecognitionUserSuggestion',
        ),
        migrations.RenameField(
            model_name='facerecognitionrectangle',
            old_name='subject_ai_guess',
            new_name='subject_ai_suggestion',
        ),
        migrations.RenameModel(
            old_name='FaceRecognitionRectangleSubjectDataGuess',
            new_name='FaceRecognitionRectangleSubjectDataSuggestion',
        ),
    ]
