# Generated by Django 2.2.17 on 2020-12-10 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik_face_recognition', '0106_auto_20201011_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognitionrectangle',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(0, 'Child'), (1, 'Adult'), (2, 'Elderly'), (3, 'Unknown'),
                                                            (4, 'Not Applicable')], null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectangle',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male'), (2, 'Unknown'),
                                                                        (3, 'Not Applicable')], null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectangle',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'User'), (1, 'Algorithm'), (2, 'Picasa')], default=1),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectanglesubjectdatasuggestion',
            name='age',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Child'), (1, 'Adult'), (2, 'Elderly'), (3, 'Unknown'), (4, 'Not Applicable')], null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectanglesubjectdatasuggestion',
            name='gender',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Female'), (1, 'Male'), (2, 'Unknown'), (3, 'Not Applicable')], null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionrectanglesubjectdatasuggestion',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_data_proposer',
                                    to='ajapaik.Profile'),
        ),
        migrations.AlterField(
            model_name='facerecognitionusersuggestion',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'User'), (1, 'Algorithm'), (2, 'Picasa')], default=1),
        ),
        migrations.AlterField(
            model_name='facerecognitionusersuggestion',
            name='rectangle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='face_recognition_suggestions',
                                    to='ajapaik_face_recognition.FaceRecognitionRectangle'),
        ),
        migrations.AlterField(
            model_name='facerecognitionusersuggestion',
            name='subject_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='face_recognition_suggestions', to='ajapaik.Album'),
        ),
        migrations.AlterField(
            model_name='facerecognitionusersuggestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='face_recognition_suggestions', to='ajapaik.Profile'),
        ),
    ]
