# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0001_squashed_0070_photo_uploader_is_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tourgroup',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tourgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='tourgroup',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourphoto',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tourphoto',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourphotoorder',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tourphotoorder',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourrephoto',
            name='original',
        ),
        migrations.RemoveField(
            model_name='tourrephoto',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourrephoto',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='touruniqueview',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='touruniqueview',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='touruniqueview',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='video',
            name='source',
        ),
        migrations.DeleteModel(
            name='CSVPhoto',
        ),
        migrations.RemoveField(
            model_name='album',
            name='is_film_still_album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name_et',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name_sv',
        ),
        migrations.RemoveField(
            model_name='album',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='name_et',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='name_sv',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='area',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_et',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_fi',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_sv',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='then_and_now_rephoto',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_et',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_fi',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_nl',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_sv',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='video',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='video_timestamp',
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=2047, null=True, verbose_name='Beskrivelse', blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_no',
            field=models.CharField(max_length=255, null=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='album',
            name='open',
            field=models.BooleanField(default=False, verbose_name='Is open'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='type',
            field=models.PositiveSmallIntegerField(default=2, choices=[(0, b'Curated'), (1, b'Re-curated'), (2, b'Manual'), (4, b'Uploaded')]),
        ),
        migrations.AlterField(
            model_name='dating',
            name='end_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, choices=[(0, 'Dag'), (1, 'M\xe5ned'), (2, '\xc5r')]),
        ),
        migrations.AlterField(
            model_name='dating',
            name='start_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, choices=[(0, 'Dag'), (1, 'M\xe5ned'), (2, '\xc5r')]),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='map_type',
            field=models.PositiveSmallIntegerField(default=0, choices=[(0, 'Google kart'), (1, 'Google satellitt'), (2, 'OpenStreetMap'), (3, 'Juks'), (4, 'Uten kart')]),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='origin',
            field=models.PositiveSmallIntegerField(default=0, choices=[(0, 'Spill'), (1, 'Kartvisning'), (2, 'Galleri'), (3, 'Permalenke'), (4, 'Kilde')]),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='type',
            field=models.PositiveSmallIntegerField(default=0, choices=[(0, 'Kart'), (1, 'EXIF'), (2, 'GPS'), (3, 'Bekreftelse'), (4, 'Gatebilde'), (5, 'Geotagg bilde')]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='Author', blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(null=True, verbose_name='Beskrivelse', blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Beskrivelse', blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_no',
            field=models.TextField(null=True, verbose_name='Beskrivelse', blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(height_field=b'height', width_field=b'width', upload_to=b'uploads', max_length=255, blank=True, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='points',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Geotag'), (1, 'Refoto'), (2, 'Opplasting av foto'), (3, 'Utvalg av foto'), (4, 'Foto re-kuratering'), (5, 'Datering'), (6, 'Bekreftelse av datering'), (7, 'Stillbilde')]),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourGroup',
        ),
        migrations.DeleteModel(
            name='TourPhoto',
        ),
        migrations.DeleteModel(
            name='TourPhotoOrder',
        ),
        migrations.DeleteModel(
            name='TourRephoto',
        ),
        migrations.DeleteModel(
            name='TourUniqueView',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
