# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajapaik', '0105_auto_20190801_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAnnotationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectAnnotationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('alternative_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ajapaik_object_recognition.ObjectAnnotationClass')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetectionAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
                ('is_manual_detection', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('detected_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik_object_recognition.ObjectAnnotationClass')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='objectannotationfeedback',
            name='object_detection_annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ajapaik_object_recognition.ObjectDetectionAnnotation'),
        ),
        migrations.AddField(
            model_name='objectannotationfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='objectannotationclass',
            name='detection_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik_object_recognition.ObjectDetectionModel'),
        ),
    ]
