# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-21 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik_object_recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectannotationclass',
            name='label',
        ),
        migrations.AddField(
            model_name='objectannotationclass',
            name='alias',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objectannotationclass',
            name='translations',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectannotationclass',
            name='wiki_data_id',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
