# Generated by Django 4.2.16 on 2026-02-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik_object_recognition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectannotationclass',
            old_name='wiki_data_id',
            new_name='wikidata_id',
        ),
    ]
