# Generated by Django 2.2.17 on 2020-12-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ajapaik', '0001_initial'),
        ('ajapaik_face_recognition', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik_face_recognition.FaceRecognitionRectangle'),
        ),
        migrations.AddField(
            model_name='points',
            name='dating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.Dating'),
        ),
        migrations.AddField(
            model_name='points',
            name='dating_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.DatingConfirmation'),
        ),
        migrations.AddField(
            model_name='points',
            name='face_recognition_rectangle_subject_data_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik_face_recognition.FaceRecognitionRectangleSubjectDataSuggestion'),
        ),
        migrations.AddField(
            model_name='points',
            name='geotag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.GeoTag'),
        ),
        migrations.AddField(
            model_name='points',
            name='image_similarity_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.ImageSimilaritySuggestion'),
        ),
        migrations.AddField(
            model_name='points',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='points',
            name='subject_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik_face_recognition.FaceRecognitionUserSuggestion'),
        ),
        migrations.AddField(
            model_name='points',
            name='transcription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.Transcription'),
        ),
        migrations.AddField(
            model_name='points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points',
                                    to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='photoviewpointelevationsuggestion',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photoviewpointelevationsuggestion',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photo_viewpoint_elevation_suggestions', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='photoscenesuggestion',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photoscenesuggestion',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photo_scene_suggestions', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='photorotationsuggestion',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photorotationsuggestion',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photo_rotate_suggestions', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='photometadataupdate',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_updates',
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photolike',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes',
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photolike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes',
                                    to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='photoinvertsuggestion',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photoinvertsuggestion',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photo_invert_suggestions', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='photoflipsuggestion',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photoflipsuggestion',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photo_flip_suggestions', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='areas', to='ajapaik.Area'),
        ),
        migrations.AddField(
            model_name='photo',
            name='back_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='back', to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.Device'),
        ),
        migrations.AddField(
            model_name='photo',
            name='front_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='front', to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.Licence'),
        ),
        migrations.AddField(
            model_name='photo',
            name='rephoto_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='rephotos', to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='similar_photos',
            field=models.ManyToManyField(through='ajapaik.ImageSimilarity', to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.Source'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photos', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='photo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='stills', to='ajapaik.Video'),
        ),
        migrations.AddField(
            model_name='imagesimilaritysuggestion',
            name='image_similarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_similarity',
                                    to='ajapaik.ImageSimilarity'),
        ),
        migrations.AddField(
            model_name='imagesimilaritysuggestion',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='image_similarity_proposer', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='imagesimilarity',
            name='from_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_photo',
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='imagesimilarity',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_photo',
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='imagesimilarity',
            name='user_last_modified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_last_modified', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='geotag',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geotags',
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='geotag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='geotags', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='difficultyfeedback',
            name='geotag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.GeoTag'),
        ),
        migrations.AddField(
            model_name='difficultyfeedback',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='difficultyfeedback',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_feedbacks',
                                    to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='datingconfirmation',
            name='confirmation_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations',
                                    to='ajapaik.Dating'),
        ),
        migrations.AddField(
            model_name='datingconfirmation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dating_confirmations',
                                    to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='dating',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datings',
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='dating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datings',
                                    to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Album'),
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='album_photo_links', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='albums', through='ajapaik.AlbumPhoto', to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='albums', to='ajapaik.Profile'),
        ),
        migrations.AddField(
            model_name='album',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ajapaik.Source'),
        ),
        migrations.AddField(
            model_name='album',
            name='subalbum_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='subalbums', to='ajapaik.Album'),
        ),
        migrations.AddField(
            model_name='album',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='albums', to='ajapaik.Video'),
        ),
        migrations.AddField(
            model_name='action',
            name='related_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='CSVPhoto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ajapaik.photo',),
        ),
        migrations.CreateModel(
            name='NorwegianCSVPhoto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ajapaik.photo',),
        ),
        migrations.AlterUniqueTogether(
            name='points',
            unique_together={('user', 'dating'), ('user', 'image_similarity_confirmation'), ('user', 'geotag'),
                             ('user', 'subject_confirmation'), ('user', 'dating_confirmation')},
        ),
    ]
