# Generated by Django 2.2.17 on 2020-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0002_auto_20201211_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name_original_language',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Name original language'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_original_language',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Description original language'),
        ),
    ]
