# Generated by Django 2.2.17 on 2020-12-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0004_auto_20201213_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVPhoto',
        ),
        migrations.DeleteModel(
            name='NorwegianCSVPhoto',
        ),
    ]
