# Generated by Django 2.2.17 on 2020-12-29 15:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0005_auto_20201217_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='muis_person_ids',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True),
                default=list,
                size=None
            ),
        ),
    ]
