# Generated by Django 2.2.17 on 2020-12-30 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0006_album_muis_person_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dating',
            name='profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='datings',
                to='ajapaik.Profile'
            ),
        ),
    ]
