# Generated by Django 2.2.17 on 2021-02-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0013_auto_20210207_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='muis_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
