# Generated by Django 2.2.17 on 2021-02-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0014_photo_muis_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Location')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='photos',
            field=models.ManyToManyField(related_name='locations', through='ajapaik.LocationPhoto', to='ajapaik.Photo'),
        ),
        migrations.AddField(
            model_name='location',
            name='sublocation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sublocations', to='ajapaik.Location'),
        ),
    ]
