# Generated by Django 2.2.17 on 2021-02-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0015_auto_20210212_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo')),
            ],
        ),
    ]
