# Generated by Django 2.2.24 on 2021-07-20 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0016_applicationexception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesimilarity',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagesimilaritysuggestion',
            name='proposer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='image_similarity_proposer',
                to='ajapaik.Profile'
            ),
        ),
    ]
