# Generated by Django 3.2.7 on 2021-11-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0018_location_google_reverse_geocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumphoto',
                                    to='ajapaik.photo'),
        ),
    ]
