# Generated by Django 3.2.12 on 2022-05-26 18:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0020_photo_rephoto_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='first_annotation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='first_comment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='first_dating',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='first_geotag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='first_like',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='first_rephoto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='first_transcription',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='first_view',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latest_annotation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latest_comment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latest_dating',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latest_geotag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latest_like',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latest_rephoto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latest_transcription',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latest_view',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('latest_annotation'), descending=True, nulls_last=True), name='latest_annotation_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_annotation'), descending=True, nulls_last=True), name='first_annotation_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('latest_transcription'), descending=True, nulls_last=True), name='latest_transcription_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_transcription'), descending=True, nulls_last=True), name='first_transcription_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('latest_dating'), descending=True, nulls_last=True), name='latest_dating_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_dating'), descending=True, nulls_last=True), name='first_dating_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('latest_geotag'), descending=True, nulls_last=True), name='latest_geotag_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_geotag'), descending=True, nulls_last=True), name='first_geotag_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('latest_like'), descending=True, nulls_last=True), name='latest_like_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_like'), descending=True, nulls_last=True), name='first_like_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('latest_view'), descending=True, nulls_last=True), name='latest_view_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_view'), descending=True, nulls_last=True), name='first_view_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('latest_comment'), descending=True, nulls_last=True), name='latest_comment_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_comment'), descending=True, nulls_last=True), name='first_comment_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('latest_rephoto'), descending=True, nulls_last=True), name='latest_rephoto_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_rephoto'), descending=True, nulls_last=True), name='first_rephoto_idx'),
        ),
    ]
