# Generated by Django 3.2.12 on 2022-05-26 19:02

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0021_auto_20220526_2153'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='photo',
            name='first_annotation_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='first_transcription_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='first_dating_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='first_geotag_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='first_like_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='first_view_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='first_comment_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='first_rephoto_idx',
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_annotation'), nulls_last=True), name='first_annotation_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_transcription'), nulls_last=True), name='first_transcription_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_dating'), nulls_last=True), name='first_dating_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_geotag'), nulls_last=True), name='first_geotag_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_like'), nulls_last=True), name='first_like_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_view'), nulls_last=True), name='first_view_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_comment'), nulls_last=True), name='first_comment_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('first_rephoto'), nulls_last=True), name='first_rephoto_idx'),
        ),
    ]
