# Generated by Django 3.2.12 on 2022-06-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0022_auto_20220526_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
