# Generated by Django 3.2.16 on 2023-04-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0024_auto_20230204_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(blank=True,
                                                help_text='To be used if only one specific source key is to be blacklisted',
                                                max_length=100, null=True, unique=True)),
                ('source_key_pattern', models.CharField(blank=True,
                                                        help_text='Supports regex, example: starts with: "collection:key*", for exact match use: source_key instead',
                                                        max_length=100, null=True, unique=True)),
                ('source_url', models.URLField(blank=True, max_length=1023, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
