# Generated by Django 3.2.20 on 2024-10-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0026_photo_soft_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikimediacommonsupload',
            name='photo',
        ),
        migrations.DeleteModel(
            name='PhotoMetadataUpdate',
        ),
        migrations.DeleteModel(
            name='WikimediaCommonsUpload',
        ),
    ]
