# Generated by Django 3.2.7 on 2023-04-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0026_photomodelsuggestionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodelsuggestionresult',
            name='proposer',
        ),
    ]
