# Generated by Django 3.2.25 on 2024-10-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0027_auto_20241021_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlemapsreversegeocode',
            name='response',
            field=models.JSONField(),
        ),
    ]
