# Generated by Django 4.2.16 on 2024-10-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0028_auto_20241022_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
