# Generated by Django 4.2.16 on 2024-10-25 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajapaik", "0029_delete_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationexception",
            name="photo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ajapaik.photo",
            ),
        ),
    ]
