# Generated by Django 3.2.7 on 2023-08-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0029_photomodelsuggestionresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photomodelsuggestionalternativecategory',
            unique_together={('proposer', 'photo_id', 'viewpoint_elevation_alternation', 'scene_alternation')},
        ),
    ]
