# Generated by Django 4.2.16 on 2026-09-09 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0030_alter_applicationexception_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorImportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_description', models.CharField(db_index=True, max_length=100)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('identifying_number', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(default=dict)),
                ('album_ids', models.JSONField(default=list)),
                ('auto_album_id', models.IntegerField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Success'), (3, 'Failed')], db_index=True, default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('result_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajapaik.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator_imports', to='ajapaik.profile')),
            ],
            options={
                'db_table': 'project_curator_import_item',
                'indexes': [models.Index(fields=['source_description', 'external_id', 'status'], name='project_cur_source__4bc2fd_idx')],
            },
        ),
    ]
