# Generated by Django 3.2.7 on 2023-08-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0030_alter_photomodelsuggestionalternativecategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photomodelsuggestionalternativecategory',
            unique_together={('proposer', 'photo_id')},
        ),
        migrations.AlterModelTable(
            name='photomodelsuggestionalternativecategory',
            table='ajapaik_photomodelsuggestionalternativecategory',
        ),
    ]
