# Generated by Django 3.2.7 on 2023-08-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0031_auto_20230809_1940'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photomodelsuggestionalternativecategory',
            table='photomodelsuggestionalternativecategory',
        ),
    ]
