# Generated by Django 3.2.7 on 2023-08-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0032_alter_photomodelsuggestionalternativecategory_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photomodelsuggestionalternativecategory',
            unique_together={('proposer', 'photo_id', 'scene_alternation')},
        ),
        migrations.AlterModelTable(
            name='photomodelsuggestionalternativecategory',
            table='ajapaik_photomodelsuggestionalternativecategory',
        ),
    ]
