# Generated by Django 3.2.7 on 2023-08-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0033_auto_20230809_1944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photomodelsuggestionalternativecategory',
            unique_together={('proposer', 'photo_id', 'viewpoint_elevation_alternation'), ('proposer', 'photo_id', 'scene_alternation')},
        ),
    ]
