# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0092_auto_20190405_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Female'), (0, 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kaart'), (1, 'EXIF'), (2, 'GPS'), (3, 'Kinnitus'), (4, 'StreetView'), (5, 'Allika geotääg'), (6, 'Android app')], default=0),
        ),
    ]
