# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0092_auto_20190405_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='perceptual_hash',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
