# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0093_auto_20190423_2323'),
        ('ajapaik', '0093_auto_20190424_0147'),
    ]

    operations = [
    ]
