# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0095_auto_20190425_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
                ('from_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_photo', to='ajapaik.Photo')),
                ('to_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_photo', to='ajapaik.Photo')),
                ('similarity_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Duplicate'), (1, 'Similar')], null=True)),
            ],
        ),
    ]
