# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0096_imagesimilarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='similar_photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='similar_photos',
            field=models.ManyToManyField(through='ajapaik.ImageSimilarity', to='ajapaik.Photo'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='confirmed_similar_photos',
        ),
    ]
