# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0097_auto_20190507_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='wikidata_qid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata identifikaator'),
        ),
    ]
