# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0099_auto_20190511_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=2047, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Naine'), (0, 'Mees')], null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='On avalik'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_de',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_et',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_fi',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_nl',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_no',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_sv',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Pealkiri'),
        ),
        migrations.AlterField(
            model_name='album',
            name='open',
            field=models.BooleanField(default=False, verbose_name='On avatud (kõik saavad pilte lisada)'),
        ),
        migrations.AlterField(
            model_name='album',
            name='wikidata_qid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata identifikaator'),
        ),
        migrations.AlterField(
            model_name='dating',
            name='end_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Päev'), (1, 'Kuu'), (2, 'Aasta')], null=True),
        ),
        migrations.AlterField(
            model_name='dating',
            name='start_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Päev'), (1, 'Kuu'), (2, 'Aasta')], null=True),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='map_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Google kaart'), (1, 'Google satelliit'), (2, 'OpenStreetMap'), (3, 'Juks'), (4, 'Pole kaardilt')], default=0),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='origin',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Mäng'), (1, 'Kaardivaade'), (2, 'Galerii'), (3, 'Püsiviide'), (4, 'Allikas'), (5, 'Ülepildistus')], default=0),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kaart'), (1, 'EXIF'), (2, 'GPS'), (3, 'Kinnitus'), (4, 'StreetView'), (5, 'Allika geotääg'), (6, 'Android rakendus')], default=0),
        ),
        migrations.AlterField(
            model_name='imagesimilarity',
            name='similarity_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Duplikaat'), (1, 'Sarnane')], null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_et',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_no',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to='uploads', verbose_name='Pilt', width_field='width'),
        ),
        migrations.AlterField(
            model_name='points',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Geotääg'), (1, 'Ülepildistus'), (2, 'Foto üleslaadimine'), (3, 'Foto kureerimine'), (4, 'Foto rekureerimine'), (5, 'Dateering'), (6, 'Dateeringu kinnitus'), (7, 'Filmikaader')], db_index=True),
        ),
    ]
