# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0100_auto_20190511_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSimilarityGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Duplikaat'), (1, 'Sarnane'), (2, 'Different')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guesser', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='guesser', to='ajapaik.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='imagesimilarity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesimilarity',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imagesimilarity',
            name='user_last_modified',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, related_name='user_last_modified', to='ajapaik.Profile'),
        ),
        migrations.AlterField(
            model_name='imagesimilarity',
            name='similarity_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Duplikaat'), (1, 'Sarnane'), (2, 'Different')], null=True),
        ),
        migrations.AddField(
            model_name='imagesimilarityguess',
            name='image_similarity',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='image_similarity', to='ajapaik.ImageSimilarity'),
        ),
    ]
