# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0101_auto_20190525_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesimilarity',
            name='similarity_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Different'), (1, 'Sarnane'), (2, 'Duplikaat')], null=True),
        ),
        migrations.AlterField(
            model_name='imagesimilarityguess',
            name='similarity_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Different'), (1, 'Sarnane'), (2, 'Duplikaat')], null=True),
        ),
    ]
