# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0102_auto_20190525_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hasSimilar',
            field=models.BooleanField(default=False),
        ),
    ]
