# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0103_photo_hassimilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
