# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0105_auto_20190812_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesimilarityguess',
            name='guesser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_similarity_guesser', to='ajapaik.Profile'),
        ),
    ]
