# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0107_auto_20190924_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mees'), (0, 'Naine')], null=True),
        ),
    ]
