# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0108_auto_20190930_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Geotääg'), (1, 'Ülepildistus'), (2, 'Foto üleslaadimine'), (3, 'Foto kureerimine'), (4, 'Foto rekureerimine'), (5, 'Dateering'), (6, 'Dateeringu kinnitus'), (7, 'Filmikaader'), (8, 'Annotatsioon'), (9, 'Kinnita subjekt'), (10, 'Kinnita piltide sarnasus'), (11, 'Hinda isiku vanust'), (12, 'Hinda isiku vanust')], db_index=True),
        ),
    ]
