# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-24 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0110_auto_20191223_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='photo',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='transcriptions', to='ajapaik.Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcription',
            name='profile',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='transcriptions', to='ajapaik.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='points',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Geotääg'), (1, 'Ülepildistus'), (2, 'Foto üleslaadimine'), (3, 'Foto kureerimine'), (4, 'Foto rekureerimine'), (5, 'Dateering'), (6, 'Dateeringu kinnitus'), (7, 'Filmikaader'), (8, 'Annotatsioon'), (9, 'Kinnita subjekt'), (10, 'Kinnita piltide sarnasus'), (11, 'Hinda isiku vanust'), (12, 'Hinda isiku vanust'), (13, 'Transcribe')], db_index=True),
        ),
    ]
