# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0111_auto_20191224_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='profile',
            new_name='user',
        ),
        migrations.AddField(
            model_name='transcription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
