# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-29 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0114_transcriptionfeedback_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionfeedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
