# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-30 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0115_auto_20191230_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
