# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-28 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0116_transcription_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Source'),
        )
    ]
