# Generated by Django 2.2.12 on 2020-05-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0117_auto_20200328_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='first_transcription',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photo',
            name='latest_transcription',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photo',
            name='transcription_count',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=True,
        )
    ]
