# Generated by Django 2.2.12 on 2020-05-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0118_auto_20200507_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='annotation_count',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photo',
            name='first_annotation',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photo',
            name='latest_annotation',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
            preserve_default=True,
        ),
    ]
