# Generated by Django 2.2.12 on 2020-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0119_auto_20200507_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlipFeedback',
        ),
    ]
