# Generated by Django 2.2.12 on 2020-06-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0120_auto_20200601_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_consent',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
