# Generated by Django 2.2.12 on 2020-06-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0121_auto_20200619_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMergeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_merge_tokens', to='ajapaik.Profile')),
            ],
        ),
    ]
