# Generated by Django 2.2.12 on 2020-07-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0122_auto_20200619_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemergetoken',
            name='target_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merged_into_profile', to='ajapaik.Profile'),
        ),
    ]
