# Generated by Django 2.2.12 on 2020-07-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0123_auto_20200708_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemergetoken',
            name='source_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merged_from_profile', to='ajapaik.Profile'),
        )
    ]
