# Generated by Django 2.2.13 on 2020-08-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0124_auto_20200708_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wikimedia_commons_rephoto_upload_consent',
            field=models.BooleanField(null=True)
        )
    ]
