# Generated by Django 2.2.13 on 2020-08-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0126_auto_20200817_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDisplayNameChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_name_changes', to='ajapaik.Profile')),
            ],
        ),
    ]
