# Generated by Django 2.2.13 on 2020-08-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0127_auto_20200818_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikimediaCommonsUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.IntegerField(editable=False, null=True)),
                ('response_data', models.TextField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('url', models.URLField(blank=True, max_length=1023, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo')),
            ],
        ),
    ]
