# Generated by Django 2.2.16 on 2020-09-06 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0128_auto_20200822_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='hasSimilar',
            new_name='has_similar',
        ),
    ]
