# Generated by Django 2.2.16 on 2020-10-08 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0132_auto_20201009_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='guess_level',
            new_name='suggestion_level',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='face_recognition_rectangle_subject_data_guess',
            new_name='face_recognition_rectangle_subject_data_suggestion',
        ),
    ]
