# Generated by Django 2.2.16 on 2020-10-11 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0133_auto_20201009_0216'),
        ('ajapaik_face_recognition', '0105_auto_20201011_1914')
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='subject_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ajapaik_face_recognition.FaceRecognitionUserSuggestion'),
        ),
    ]

