# Generated by Django 2.2.16 on 2020-10-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0134_auto_20201011_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Geotag'), (1, 'Rephoto'), (2, 'Photo upload'), (3, 'Photo curation'), (4, 'Photo re-curation'), (5, 'Dating'), (6, 'Dating confirmation'), (7, 'Film still'), (8, 'Annotation'), (9, 'Confirm subject'), (10, 'Confirm Image similarity'), (11, 'Suggestion subject age'), (12, 'Suggestion subject age'), (13, 'Transcribe'), (14, 'Categorize scene')], db_index=True),
        ),
    ]
