# Generated by Django 2.2.16 on 2020-10-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0135_auto_20201016_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera_elevation',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(0, 'Ground level'), (1, 'Raised'), (2, 'Aerial')],
                                                   null=True, verbose_name='Camera elevation'),
        ),
        migrations.CreateModel(
            name='PhotoCameraElevationSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('camera_elevation', models.PositiveSmallIntegerField(blank=True,
                                                                      choices=[(0, 'Ground level'), (1, 'Raised'),
                                                                               (2, 'Aerial')], null=True,
                                                                      verbose_name='Camera elevation')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo')),
                ('proposer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='photo_camera_elevation_suggestions',
                                               to='ajapaik.Profile')),
            ],
        ),
    ]
