# Generated by Django 2.2.16 on 2020-10-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0136_auto_20201017_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Geotag'), (1, 'Rephoto'), (2, 'Photo upload'), (3, 'Photo curation'), (4, 'Photo re-curation'), (5, 'Dating'), (6, 'Dating confirmation'), (7, 'Film still'), (8, 'Annotation'), (9, 'Confirm subject'), (10, 'Confirm Image similarity'), (11, 'Suggestion subject age'), (12, 'Suggestion subject age'), (13, 'Transcribe'), (14, 'Categorize scene'), (15, 'Add camera elevation')], db_index=True),
        ),
    ]
