# Generated by Django 2.2.16 on 2020-10-19 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0138_auto_20201019_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='PhotoViewpointElevationSuggestion',
            old_name='camera_elevation',
            new_name='viewpoint_elevation'
        ),
    ]
