# Generated by Django 2.2.16 on 2020-10-19 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajapaik', '0139_auto_20201019_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='viewpoint_elevation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Ground'), (1, 'Raised'), (2, 'Aerial')], null=True, verbose_name='Viewpoint elevation'),
        ),
        migrations.AlterField(
            model_name='photoviewpointelevationsuggestion',
            name='viewpoint_elevation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Ground'), (1, 'Raised'), (2, 'Aerial')], null=True, verbose_name='Viewpoint elevation'),
        ),
    ]
