# Generated by Django 2.2.16 on 2020-10-27 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0140_auto_20201019_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRotationSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rotated', models.IntegerField(blank=True, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo')),
                ('proposer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='photo_rotate_suggestions', to='ajapaik.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoInvertSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invert', models.NullBooleanField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo')),
                ('proposer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='photo_invert_suggestions', to='ajapaik.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoFlipSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('flip', models.NullBooleanField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajapaik.Photo')),
                ('proposer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='photo_flip_suggestions', to='ajapaik.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
