# Generated by Django 2.2.16 on 2020-10-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0141_auto_20201027_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='action',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Geotag'), (1, 'Rephoto'), (2, 'Photo upload'), (3, 'Photo curation'),
                         (4, 'Photo re-curation'), (5, 'Dating'), (6, 'Dating confirmation'), (7, 'Film still'),
                         (8, 'Annotation'), (9, 'Confirm subject'), (10, 'Confirm Image similarity'),
                         (11, 'Suggestion subject age'), (12, 'Suggestion subject age'), (13, 'Transcribe'),
                         (14, 'Categorize scene'), (15, 'Add viewpoint elevation'), (16, 'Flip photo'),
                         (18, 'Invert photo'), (17, 'Rotate photo')], db_index=True),
        ),
    ]
