# Generated by Django 2.2.16 on 2020-12-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0142_auto_20201027_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name_lt',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='album',
            name='name_lv',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='area',
            name='name_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='name_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_lt',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_lv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_lt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_lv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
