# Generated by Django 2.2.17 on 2020-12-10 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajapaik', '0143_auto_20201201_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='atype',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Curated'), (1, 'Favorites'), (2, 'Auto'), (3, 'Person'), (4, 'Collection')]),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=2047, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], null=True,
                                                   verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_de',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_et',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_fi',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_nl',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_no',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_sv',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='open',
            field=models.BooleanField(default=False, verbose_name='Is open'),
        ),
        migrations.AlterField(
            model_name='album',
            name='wikidata_qid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata identifier'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Curated'), (1, 'Re-curated'), (2, 'Manual'), (3, 'Still'), (4, 'Uploaded'),
                         (5, 'Face tagged'), (6, 'Collection')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='dating',
            name='end_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Day'), (1, 'Month'), (2, 'Year')],
                                                   null=True),
        ),
        migrations.AlterField(
            model_name='dating',
            name='start_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Day'), (1, 'Month'), (2, 'Year')],
                                                   null=True),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='map_type',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Google map'), (1, 'Google satellite'), (2, 'OpenStreetMap'), (3, 'Juks'), (4, 'No map')],
                default=0),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='origin',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Game'), (1, 'Map view'), (2, 'Gallery'), (3, 'Permalink'), (4, 'Source'), (5, 'Rephoto')],
                default=0),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Map'), (1, 'EXIF'), (2, 'GPS'), (3, 'Confirmation'), (4, 'StreetView'),
                         (5, 'Source geotag'), (6, 'Android app')], default=0),
        ),
        migrations.AlterField(
            model_name='imagesimilarity',
            name='similarity_type',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(0, 'Different'), (1, 'Similar'), (2, 'Duplicate')],
                                                   null=True),
        ),
        migrations.AlterField(
            model_name='imagesimilaritysuggestion',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='image_similarity_proposer', to='ajapaik.Profile'),
        ),
        migrations.AlterField(
            model_name='imagesimilaritysuggestion',
            name='similarity_type',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(0, 'Different'), (1, 'Similar'), (2, 'Duplicate')],
                                                   null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='back_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='back', to='ajapaik.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_et',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_no',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='front_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='front', to='ajapaik.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to='uploads',
                                    verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='photoviewpointelevationsuggestion',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photo_viewpoint_elevation_suggestions', to='ajapaik.Profile'),
        ),
    ]
