[uwsgi]
master = true
single-interpreter = true

chdir = /home/ajapaik/ajapaik-web
home = /home/ajapaik/ajapaik-web/venv
module = wsgi:application

; process model
processes = 32
cheaper = 8
cheaper-algo = busyness
cheaper-overload = 10
cheaper-busyness-min = 5
cheaper-busyness-max = 20
cheaper-busyness-multiplier = 10
cheaper-busyness-penalty = 3
cheaper-busyness-backlog-alert = 1

; threads (start conservative)
enable-threads = true
threads = 1

; safety / recycling
harakiri = 120
harakiri-verbose = true
max-requests = 1000
max-requests-delta = 200
reload-mercy = 120
worker-reload-mercy = 120
mule-reload-mercy = 120

; socket
protocol = uwsgi
socket = /home/ajapaik/ajapaik-web/run/app.sock
chmod-socket = 660
vacuum = true
listen = 1024
thunder-lock = true

; nginx large headers / query strings
buffer-size = 65536

; run as unprivileged
gid = www-data