# uWSGI configuration file for use together with Dockerfile
[uwsgi]
master
harakiri = 120
max-requests = 200
single-interpreter

# Graceful shutdown
#hook-master-start = unix_signal:15 gracefully_kill_them_all
#reload-mercy = 120
#worker-reload-mercy = 120
#mule-reload-mercy = 120

# Socket
protocol = uwsgi
socket = /home/ajapaik/ajapaik-web/run/app.sock
chmod-socket = 666

# HTTP - allow larger request query strings
buffer-size = 65536

# Adaptive process spawning https://uwsgi-docs.readthedocs.io/en/latest/Cheaper.html
# Min-workers
cheaper = 4
# Max workers
processes = 40
cheaper-algo = busyness
cheaper-overload = 10
cheaper-busyness-max = 10
cheaper-busyness-min = 5
cheaper-busyness-multiplier = 10
cheaper-busyness-penalty = 3
cheaper-busyness-backlog-alert = 1

# Ajapaik old conf
logto = /var/log/ajapaik/production/uwsgi.log
max-worker-lifetime = 3600
reload-on-rss = 1024
worker-reload-mercy = 60
chdir = /home/ajapaik/ajapaik-web

# Python
virtualenv = /home/ajapaik/ajapaik-web/venv
module = ajapaik.wsgi:application
enable-threads
