;supress inspection "DuplicateKeyInSection" for whole file
[uwsgi]
master
harakiri = 120
max-requests = 2000
max-worker-lifetime = 3600
reload-on-rss = 4096
worker-reload-mercy = 60
chdir = /home/ajapaik/ajapaik-web
single-interpreter
die-on-term = true
need-app = true

# Graceful shutdown
hook-master-start = unix_signal:15 gracefully_kill_them_all
reload-mercy = 120
worker-reload-mercy = 120
mule-reload-mercy = 120

# Socket
protocol = uwsgi
socket = /home/ajapaik/ajapaik-web/run/app.sock
chmod-socket = 666
thunder-lock = true
vacuum = true
lister = 1024

# HTTP - allow larger request query strings
buffer-size = 65536

# Adaptive process spawning https://uwsgi-docs.readthedocs.io/en/latest/Cheaper.html
# Min-workers
cheaper = 4
# Max workers
processes = 25
cheaper-algo = busyness
cheaper-overload = 10
cheaper-busyness-max = 10
cheaper-busyness-min = 5
cheaper-busyness-multiplier = 10
cheaper-busyness-penalty = 3
cheaper-busyness-backlog-alert = 1

# Python
virtualenv = /home/ajapaik/ajapaik-web/venv
module = wsgi:application

uid = 1010
gid = www-data